IoProtocol: add missing space after closing brace of SAioRtdScaling
checkpatch complains about missing space:

    ERROR: space required after that close brace '}'

Add this space between the closing brace of the struct and the __packed
annotation.

Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>