fix: Add missing header pinconf-generic.h to revpi_core.c
When building the picontrol-dkms package with a 6.6 kernel the following
error breaks the build:
> revpi_core.c:262:17: error: implicit declaration of function ‘pinconf_to_config_packed’

pinconf_to_config_packed() and PIN_CONFIG_BIAS_PULL_DOWN are defined in
linux/pinctrl/pinconf-generic.h. Add this to the include headers. And
sort the include headers in alphabetical order.

Fixes: da39a2b4745a ("Configure a pull-down to Sniff2A pin")
Signed-off-by: Philipp Rosenberger <p.rosenberger@kunbus.com>