revpi_flat: ensure space after comma
Checkpatch complains that a comma should be followed by a space:

    ERROR: space required after that ',' (ctx:VxV)
    #200: FILE: src/revpi_flat.c:200:
    +				dev_err(piDev_g.dev,"Failed to get cpu "
    				                   ^

Fix this by introducing the missing space.

Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>